// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckFieldSchema } from "./CheckFieldSchema";

export type CheckSchemaResponse = { name: string, description: string, fields: Array<CheckFieldSchema>, };
