// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckFieldValue } from "./CheckFieldValue";

export type CheckFieldSchema = { name: string, description: string | null, default: CheckFieldValue, };
