// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CheckFieldValue = { "String": string } | { "Username": string } | { "Password": string } | { "Number": number } | { "Percentage": number } | { "Float": number } | { "Duration": number } | { "Timeout": number } | { "Port": number } | { "IPAddrk": string };
